# Generated by Django 3.1.4 on 2021-06-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210609_1556'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='application',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='application', to='user.application'),
            preserve_default=False,
        ),
    ]
