# Generated by Django 3.2.3 on 2021-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(max_length=128)),
                ('blogBody', models.TextField()),
                ('blogDesc', models.TextField()),
                ('blogPhoto', models.ImageField(blank=True, upload_to='image/%Y/%m/%d')),
            ],
        ),
    ]
