# Generated by Django 3.1.7 on 2021-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfGuest', models.CharField(max_length=300)),
                ('question', models.TextField()),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
            ],
        ),
    ]
