# Generated by Django 3.1.4 on 2021-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfClient', models.CharField(max_length=300)),
                ('emailOfClient', models.CharField(max_length=300)),
                ('phoneOfClient', models.CharField(max_length=300)),
                ('kindOfEvent', models.CharField(max_length=300)),
                ('purposeOfEvent', models.CharField(max_length=300)),
                ('dateTimeOfEvent', models.CharField(max_length=300)),
                ('budgetOfEvent', models.CharField(max_length=300)),
                ('placeOfEvent', models.CharField(max_length=300)),
                ('numberOfGuests', models.CharField(max_length=300)),
                ('ageOfGuests', models.CharField(max_length=300)),
                ('periodOfPreparation', models.TextField()),
                ('addInfo', models.TextField()),
                ('findOut', models.CharField(max_length=300)),
            ],
        ),
    ]
