# Generated by Django 3.1.4 on 2021-06-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210609_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='newInfo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
