# Generated by Django 3.1.4 on 2021-06-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210609_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='newInfo',
        ),
        migrations.AlterField(
            model_name='application',
            name='kindOfEvent',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='placeOfEvent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='purposeOfEvent',
            field=models.TextField(),
        ),
    ]
