# Generated by Django 3.1.7 on 2021-06-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210615_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='email',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
